core:
  software:
    charms:
      cinder-volume:
        channel: 2024.1/stable
      cinder-volume-ceph:
        channel: 2024.1/stable
      cinder-k8s:
        channel: 2024.1/stable
      glance-k8s:
        channel: 2024.1/stable
      horizon-k8s:
        channel: 2024.1/stable
      keystone-k8s:
        channel: 2024.1/stable
      neutron-k8s:
        channel: 2024.1/stable
      nova-k8s:
        channel: 2024.1/stable
      openstack-hypervisor:
        channel: 2024.1/stable
        config:
          snap-channel: 2024.1/stable
      ovn-central-k8s:
        channel: 24.03/stable
      ovn-relay-k8s:
        channel: 24.03/stable
      placement-k8s:
        channel: 2024.1/stable
      sunbeam-clusterd:
        channel: 2024.1/stable
        config:
          snap-channel: 2024.1/stable
      sunbeam-machine:
        channel: 2024.1/stable
      microceph:
        channel: squid/stable
        config:
          snap-channel: squid/stable
features:
  caas:
    software:
      charms:
        magnum-k8s:
          channel: 2024.1/stable
  dns:
    software:
      charms:
        designate-bind-k8s:
          channel: 9/stable
        designate-k8s:
          channel: 2024.1/stable
  images-sync:
    software:
      charms:
        openstack-images-sync-k8s:
          channel: 2024.1/stable
  instance-recovery:
    software:
      charms:
        consul-k8s:
          channel: 1.19/edge
        consul-client:
          channel: 1.19/edge
        masakari-k8s:
          channel: 2024.1/stable
  ldap:
    software:
      charms:
        keystone-ldap-k8s:
          channel: 2024.1/stable
  loadbalancer:
    software:
      charms:
        octavia-k8s:
          channel: 2024.1/stable
  orchestration:
    software:
      charms:
        heat-k8s:
          channel: 2024.1/stable
  resource-optimization:
    software:
      charms:
        watcher-k8s:
          channel: 2024.1/stable
  secrets:
    software:
      charms:
        barbican-k8s:
          channel: 2024.1/stable
  telemetry:
    software:
      charms:
        aodh-k8s:
          channel: 2024.1/stable
        ceilometer-k8s:
          channel: 2024.1/stable
        gnocchi-k8s:
          channel: 2024.1/stable
        openstack-exporter-k8s:
          channel: 2024.1/stable
  validation:
    software:
      charms:
        tempest-k8s:
          channel: 2024.1/stable
